### ISSUE TITLE
feature request: create

### ISSUE THREAD

**Issue by Kampe** [iRoachie/slack-github-actions#14]
Thank you for your action! It's very useful and looks great!

Do have a feature request potentially, saw there's a message output on `create` that it's not supported yet. However that would be super useful to have!

**Comment by iRoachie** [comment]
Sure! Sounds like a good idea. Will begin working on it

**Comment by iRoachie** [comment]
Added in v2.2.0 🎉 . Thanks for your suggestion.

**Comment by Kampe** [comment]
You're the best, thanks!
