### ISSUE TITLE
Feature Request: Delete Branch

### ISSUE THREAD

**Issue by Kampe** [iRoachie/slack-github-actions#16]
Hey again!

Wondering if it's possible to add support for branch deletion?  Just added it myself and noticed that I get the same message as create :P 

Really appreciate the work!

**Comment by iRoachie** [comment]
Sure thing! Will look at it over the weekend

**Comment by Kampe** [comment]
Awesome, seriously, thanks again! I've tried all the slack actions, and this is by far the best! :)

**Comment by iRoachie** [comment]
Added in v2.3.0 🎉 . Thanks again

**Comment by Kampe** [comment]
thank you!
