### ISSUE TITLE
[Feature Request] Slack mentions

### ISSUE THREAD

**Issue by tsaodown** [iRoachie/slack-github-actions#19]
Would really like to notify specific users of build failures. Any chance we could integrate that kind of functionality?

Could use a github user -> slack userr mapping like in this action: https://github.com/abeyuya/actions-mention-to-slack

**Comment by tsaodown** [comment]
If necessary I could implement and submit a PR

**Comment by iRoachie** [comment]
Hey it looks cool but I think it might be out of scope for this project. Passing custom messages is not something I wanted for this project
